### ISSUE TITLE
incompatible with higher version mmcv

### ISSUE THREAD

**Issue by florinshen** [open-mmlab/mmselfsup#119]
Environment:
torch: torch1.8.1 + cuda9.0
mmcv: mmcv-full 1.3.7
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.4/lib/python3.6/tempfile.py", line 452, in __del__
    self.close()
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.4/lib/python3.6/tempfile.py", line 448, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp5r2wtas6/tmpoaxguqmv.py'
Exception ignored in: <bound method _TemporaryFileCloser.__del__ of <tempfile._TemporaryFileCloser object at 0x7f8bee856cf8>>
Traceback (most recent call last):
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.4/lib/python3.6/tempfile.py", line 452, in __del__
    self.close()
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.4/lib/python3.6/tempfile.py", line 448, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp7gc3z8k7/tmpk1a5c646.py'
Exception ignored in: <bound method _TemporaryFileCloser.__del__ of <tempfile._TemporaryFileCloser object at 0x7f1f43c35cf8>>
Traceback (most recent call last):
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.4/lib/python3.6/tempfile.py", line 452, in __del__
Exception ignored in: <bound method _TemporaryFileCloser.__del__ of <tempfile._TemporaryFileCloser object at 0x7f81a29d2eb8>>
Traceback (most recent call last):
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.4/lib/python3.6/tempfile.py", line 452, in __del__
    self.close()
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.4/lib/python3.6/tempfile.py", line 448, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmprvu591pk/tmpar8yat8x.py'
    self.close()
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.4/lib/python3.6/tempfile.py", line 448, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpzamtod_6/tmprw1g7cfo.py'
Exception ignored in: <bound method _TemporaryFileCloser.__del__ of <tempfile._TemporaryFileCloser object at 0x7fc234353e10>>
Traceback (most recent call last):
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.4/lib/python3.6/tempfile.py", line 452, in __del__
    self.close()
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.4/lib/python3.6/tempfile.py", line 448, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp4bi6a_9o/tmpuiwdsc45.py'
Exception ignored in: <bound method _TemporaryFileCloser.__del__ of <tempfile._TemporaryFileCloser object at 0x7ff5fa062e48>>
Traceback (most recent call last):
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.4/lib/python3.6/tempfile.py", line 452, in __del__
    self.close()
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.4/lib/python3.6/tempfile.py", line 448, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp5z3t0qqp/tmp4kf4rv_b.py'

**Comment by Jiahao000** [comment]
Did you exactly follow [INSTALL.md](https://github.com/open-mmlab/OpenSelfSup/blob/master/docs/INSTALL.md) for installation?
