### ISSUE TITLE
Error when running linear evaluation on CIFAR with pre-trained ResNet50

### ISSUE THREAD

**Issue by liming-ai** [open-mmlab/mmselfsup#186]
I try to running linear evaluation with resnet50 pre-trained on mocov2, the command is:
```
GPUS=1 bash tools/benchmarks/classification/dist_train_linear.sh configs/benchmarks/classification/cifar/resnet50_8xb128-steplr-350e_cifar10.py work_dirs/selfsup/mocov2/mocov2_resnet50_8xb32-coslr-200e_in1k/extracted_epoch_200.pth --work_dir work_dirs/benchmark/cifar/mocov2_resnet50_8xb32-coslr-200e_in1k/epoch_200
```

The error informations are:
```
Traceback (most recent call last):
  File "tools/train.py", line 158, in <module>
    main()
  File "tools/train.py", line 154, in main
    meta=meta)
  File "/home/tiger/code/ssl/SelfSup/mmselfsup/apis/train.py", line 186, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/home/tiger/.local/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/tiger/.local/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 434, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/tiger/code/ssl/SelfSup/mmselfsup/datasets/single_view.py", line 30, in __getitem__
    img = self.data_source.get_img(idx)
  File "/home/tiger/code/ssl/SelfSup/mmselfsup/datasets/data_sources/base.py", line 86, in get_img
    if self.data_infos[idx]['img_prefix'] is not None:
KeyError: 'img_prefix'
```

**Comment by fangyixiao18** [comment]
Thank you for your issue. Actually, as all cifar pictures has been loaded to memory here https://github.com/open-mmlab/mmselfsup/blob/master/mmselfsup/datasets/data_sources/cifar.py , it is no need to load again and the key for cifar image is 'img'. It is a bug due to our negligence.
You can modify your code for simple run 
```python
if self.data_infos[idx].get('img_prefix', None) is not None:
    if self.data_infos[idx]['img_prefix'] is not None:
                filename = osp.join(self.data_infos[idx]['img_prefix'],
                                    self.data_infos[idx]['img_info']['filename'])
            else:
                filename = self.data_infos[idx]['img_info']['filename']
    
            img_bytes = self.file_client.get(filename)
            img = mmcv.imfrombytes(img_bytes, flag=self.color_type)
else:
    img = self.data_infos[idx]['img']

img = img.astype(np.uint8)
return Image.fromarray(img)
  ```
you can try the code above.
If it works, welcome to create a PR to fix it!

The datasets part will be refactored in the following months to align it with other MM projects.

**Comment by liming-ai** [comment]
It works and I have created a PR to fix it
