### ISSUE TITLE
Error when  prefetch enabled in linear classification

### ISSUE THREAD

**Issue by 4-0-4-notfound** [open-mmlab/mmselfsup#254]
Thanks for reporting the unexpected results and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The unexpected results still exist in the latest version.

**Describe the Issue**
A clear and concise description of what the bug is, including what results are expected and what the real results you got.

**Reproduction**

1. What command, code, or script did you run?

```bash
bash tools/benchmarks/classification/slurm_train_linear.sh test test configs/benchmarks/classification/imagenet/resnet50_8xb32-steplr-100e_in1k.py checkpoint
```

2. Did you make any modifications on the code? Did you understand what you have modified?

`set prefetch =True in configs/benchmarks/classification/_base_/datasets/imagenet.py`

**Environment**

1. Please run `python -c "from mmselfsup.utils import collect_env; print(collect_env())"` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

```none
2022-03-26 19:39:22,385 - mmselfsup - INFO - Environment info:                                                                                                                                                    ------------------------------------------------------------                                                                                                                                                      sys.platform: linux                                                                                                                                                                                               Python: 3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0]
CUDA available: True
GPU 0: Tesla PG503-216
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.2.r11.2/compiler.29618528_0
GCC: gcc (GCC) 5.4.0
PyTorch: 1.9.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.10.0+cu111
OpenCV: 4.5.5
MMCV: 1.4.2
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMSelfSup: 0.7.1+16d9bf2
------------------------------------------------------------
```

**Error traceback**
If applicable, paste the error traceback here.

```none
2022-03-26 19:39:24,483 - mmselfsup - INFO - initialize ClsHead with init_cfg [{'type': 'Normal', 'std': 0.01, 'layer': 'Linear'}, {'type': 'Constant', 'val': 1, 'layer': ['_BatchNorm', 'GroupNorm']}]  [25/514]
/mnt/lustre/xxx/github/mmselfup071/mmselfsup/datasets/base.py:29: UserWarning: The dataset part will be refactored, it will soon support `dict` in pipelines to save more information, the same as the pipeline in `MMDet`.
  warnings.warn('The dataset part will be refactored, it will soon '
Traceback (most recent call last):
  File "tools/train.py", line 199, in <module>
    main()
  File "tools/train.py", line 189, in main
    train_model(
  File "/mnt/lustre/xxx/github/mmselfup071/mmselfsup/apis/train.py", line 192, in train_model
    eval_hook(val_dataloader, test_fn=eval_fn, **eval_cfg),
  File "/mnt/cache/xxx/anaconda3/envs/densecl_19/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 460, in __init__
    super().__init__(
  File "/mnt/cache/xxx/anaconda3/envs/densecl_19/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 99, in __init__
    raise TypeError(f'dataloader must be a pytorch DataLoader, '
TypeError: dataloader must be a pytorch DataLoader, but got <class 'mmselfsup.datasets.utils.PrefetchLoader'>
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by fangyixiao18** [comment]
As our prefetch loader is a wrapper, which is not the type of pytorch `Dataloader` (you can check https://github.com/open-mmlab/mmselfsup/blob/master/mmselfsup/datasets/utils.py#L163), but mmcv evaluation hook will check it.  
It currently does not support evaluation.
