### ISSUE TITLE
ModuleNotFoundError when training mmdet after using detectron2

### ISSUE THREAD

**Issue by liming-ai** [open-mmlab/mmselfsup#301]
@fangyixiao18, @Jiahao000 , @XiaohangZhan 

Thanks for reporting the unexpected results and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The unexpected results still exist in the latest version.

**Describe the Issue**
The mmdet works fine at first, however, after I installed the detectron2 and finished detectron2 benchmarks, the mmdet benchmarks with Mask RCNN-C4 failed. But Mask RCNN-FPN still work fine.

I have tried to re-install mmdet/openmim/mmcv-full, but it did not work.

**Reproduction**

I run the VOC detection benchmarks with detectron2, then mim/mmdet failed.

**Environment**

1. Please run `python -c "from mmselfsup.utils import collect_env; print(collect_env())"` to collect necessary environment information and paste it here.
```
{'sys.platform': 'linux', 'Python': '3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]', 'CUDA available': True, 'GPU 0,1,2,3,4,5,6,7': 'Tesla V100-SXM2-32GB', 'CUDA_HOME': '/usr/local/cuda', 'NVCC': 'Cuda compilation tools, release 11.3, V11.3.109', 'GCC': 'x86_64-linux-gnu-gcc (Debian 8.3.0-6) 8.3.0', 'PyTorch': '1.10.0', 'PyTorch compiling details': 'PyTorch built with:\n  - GCC 7.3\n  - C++ Version: 201402\n  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX512\n  - CUDA Runtime 11.3\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86\n  - CuDNN 8.2\n  - Magma 2.5.2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, \n', 'TorchVision': '0.11.1+cu113', 'OpenCV': '4.5.5', 'MMCV': '1.5.0', 'MMCV Compiler': 'GCC 7.3', 'MMCV CUDA Compiler': '11.3', 'MMSelfSup': '0.8.0+1efcfa3'}
```
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

```
+ CFG=configs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco.py
+ PRETRAIN=work_dirs/mmselfsup/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k/final_model.pth
+ GPUS=8
+ PY_ARGS='--work-dir work_dirs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k'
++ echo configs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco
++ sed -e s/configs/work_dirs/g
++ echo work_dirs/mmselfsup/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k/final_model.pth
++ rev
++ cut -d/ -f 1
++ rev
+ WORK_DIR=work_dirs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco/final_model.pth
++ dirname tools/benchmarks/mmdetection/mim_dist_train_c4.sh
+ PYTHONPATH=tools/benchmarks/mmdetection/..::/opt/tiger/arnold_toolbox
+ mim train mmdet configs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco.py --launcher pytorch -G 8 --work-dir work_dirs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco/final_model.pth --cfg-options model.backbone.init_cfg.type=Pretrained model.backbone.init_cfg.checkpoint=work_dirs/mmselfsup/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k/final_model.pth model.roi_head.shared_head.init_cfg.type=Pretrained model.roi_head.shared_head.init_cfg.checkpoint=work_dirs/mmselfsup/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k/final_model.pth --work-dir work_dirs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k
Using port 24497 for synchronization.
Training command is python -m torch.distributed.launch --nproc_per_node=8 --master_port=24497 /home/tiger/.local/lib/python3.7/site-packages/mmdet/.mim/tools/train.py configs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco.py --launcher pytorch --work-dir work_dirs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco/final_model.pth --cfg-options model.backbone.init_cfg.type=Pretrained model.backbone.init_cfg.checkpoint=work_dirs/mmselfsup/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k/final_model.pth model.roi_head.shared_head.init_cfg.type=Pretrained model.roi_head.shared_head.init_cfg.checkpoint=work_dirs/mmselfsup/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k/final_model.pth --work-dir work_dirs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k.
/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  FutureWarning,
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
torch.distributed: socket accepted connection from 127.0.0.1:47610
torch.distributed: socket accepted connection from 127.0.0.1:47612
Traceback (most recent call last):
  File "/home/tiger/.local/lib/python3.7/site-packages/mmcv/utils/misc.py", line 73, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tools.benchmarks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tiger/.local/lib/python3.7/site-packages/mmdet/.mim/tools/train.py", line 237, in <module>
    main()
  File "/home/tiger/.local/lib/python3.7/site-packages/mmdet/.mim/tools/train.py", line 110, in main
    cfg = Config.fromfile(args.config)
  File "/home/tiger/.local/lib/python3.7/site-packages/mmcv/utils/config.py", line 340, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/home/tiger/.local/lib/python3.7/site-packages/mmcv/utils/misc.py", line 80, in import_modules_from_strings
    raise ImportError
ImportError

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 965536 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 965532) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

Traceback (most recent call last):
  File "/home/tiger/.local/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/tiger/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/tiger/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/tiger/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tiger/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tiger/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/tiger/.local/lib/python3.7/site-packages/mim/commands/train.py", line 107, in cli
    other_args=other_args)
  File "/home/tiger/.local/lib/python3.7/site-packages/mim/commands/train.py", line 256, in train
    cmd, env=dict(os.environ, MASTER_PORT=str(port)))
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '-m', 'torch.distributed.launch', '--nproc_per_node=8', '--master_port=24497', '/home/tiger/.local/lib/python3.7/site-packages/mmdet/.mim/tools/train.py', 'configs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco.py', '--launcher', 'pytorch', '--work-dir', 'work_dirs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco/final_model.pth', '--cfg-options', 'model.backbone.init_cfg.type=Pretrained', 'model.backbone.init_cfg.checkpoint=work_dirs/mmselfsup/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k/final_model.pth', 'model.roi_head.shared_head.init_cfg.type=Pretrained', 'model.roi_head.shared_head.init_cfg.checkpoint=work_dirs/mmselfsup/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k/final_model.pth', '--work-dir', 'work_dirs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k']' returned non-zero exit status 1.
```

**Bug fix**
This import error is caused by `tools.benchmarks.mmdetection.res_layer_extra_norm` in [this line](https://github.com/open-mmlab/mmcv/blob/9f5a03dc2ca3731b2c1b18f90f826fcb9eb51ccf/mmcv/utils/misc.py#L80)

```
    for imp in imports:
        if not isinstance(imp, str):
            raise TypeError(
                f'{imp} is of type {type(imp)} and cannot be imported.')
        try:
            imported_tmp = import_module(imp)
        except ImportError:
            if allow_failed_imports:
                warnings.warn(f'{imp} failed to import and is ignored.',
                              UserWarning)
                imported_tmp = None
            else:
                print(imp)   # the output is `tools.benchmarks.mmdetection.res_layer_extra_norm`
                raise ImportError
        imported.append(imported_tmp)
```

**Comment by liming-ai** [comment]
We can fix it by uninstalling the detectron2 in the current environment.

If we want to use detectron2 to benchmark, we can create a new conda environment with detectron2
