### ISSUE TITLE
RecursionError: Caught RecursionError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by Dejavuvvw** [open-mmlab/mmselfsup#328]
I don't know why this error occurs.
I modified the dataset and data_source for my dataset.
I have checked my dataset, there is no data.

The error is here:
```
Traceback (most recent call last):
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/site-packages/ipdb/__main__.py", line 305, in main
    pdb._runscript(mainpyfile)
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/pdb.py", line 1573, in _runscript
    self.run(statement)
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/mmselfsup/tools/train.py", line 2, in <module>
    from __future__ import division
  File "/home/mmselfsup/tools/train.py", line 188, in main
    train_model(
  File "/home/mmselfsup/mmselfsup/apis/train.py", line 216, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 130, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RecursionError: Caught RecursionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 79, in collate
    return {
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 80, in <dictcomp>
    key: collate([d[key] for d in batch], samples_per_gpu)
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 77, in collate
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 77, in <listcomp>
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 77, in collate
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 77, in <listcomp>
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 77, in collate
    return [collate(samples, samples_per_gpu) for samples in transposed]
  ........
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 77, in collate
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 77, in <listcomp>
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 23, in collate
    if not isinstance(batch, Sequence):
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/abc.py", line 98, in __instancecheck__
    return _abc_instancecheck(cls, instance)
  File "/home/anaconda3/envs/mmlab-selfsup/lib/python3.8/abc.py", line 102, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
RecursionError: maximum recursion depth exceeded
```

The related config is as follows:
```
data_source = 'Mine'
dataset_type = 'MultiModalDataset'
img_norm_cfg = dict(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
train_pipeline = [
    dict(
        type='RandomResizedCrop', size=224, scale=(0.2, 1.0), interpolation=3),
    dict(type='RandomHorizontalFlip'),
    dict(type='ToTensor'),
    dict(
        type='Normalize',
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225])
]
prefetch = False
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=4,
    train=dict(
        type='MultiModalDataset',
        data_source=dict(
            type='Mine',
            data_prefix='.....',
            ann_file='........'),
        pipeline=[
            dict(
                type='RandomResizedCrop',
                size=224,
                scale=(0.2, 1.0),
                interpolation=3),
            dict(type='RandomHorizontalFlip'),
            dict(type='ToTensor'),
            dict(
                type='Normalize',
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225])
        ],
        prefetch=False))
runner = dict(type='EpochBasedRunner', max_epochs=400)
checkpoint_config = dict(interval=1, max_keep_ckpts=3, out_dir='')
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
cudnn_benchmark = True
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
persistent_workers = False
opencv_num_threads = 0
mp_start_method = 'fork'
fp16 = dict(loss_scale='dynamic')
work_dir = './work_dirs/configs/crossmae_vit-base-p16_8xb512-coslr-400e_in1k'
auto_resume = False
gpu_ids = range(0, 1)
```
I created my data_source file and modified the get_img and load_annotations function:
```
    def get_img(self, idx):
        if self.file_client is None:
            self.file_client = mmcv.FileClient(**self.file_client_args)

        filename_rgb = osp.join(
            self.data_infos[idx]['img_prefix'],
            self.data_infos[idx]['rgb_info']['filename'])
        filename_thermal = osp.join(
            self.data_infos[idx]['img_prefix'],
            self.data_infos[idx]['thermal_info']['filename'])
        img_bytes_rgb = self.file_client.get(filename_rgb)
        img_bytes_t = self.file_client.get(filename_thermal)
        rgb = mmcv.imfrombytes(
            img_bytes_rgb,
            flag=self.color_type,
            channel_order=self.channel_order)
        thermal = mmcv.imfrombytes(
            img_bytes_t,
            flag=self.thermal_type,
            channel_order=self.channel_order)

        rgb = rgb.astype(np.uint8)
        thermal = thermal.astype(np.uint8)
        thermal = np.expand_dims(thermal, 2).repeat(3, axis=2)
        rgb = Image.fromarray(rgb)
        thermal = Image.fromarray(thermal)
        return rgb, thermal

    def load_annotations(self):
        if isinstance(self.ann_file, str):
            samples_rgb = []
            samples_thermal = []
            rgb_first = []
            with open(self.ann_file) as f:
                for x in f.readlines():
                    x = x.strip()
                    if 'rgb' in x:
                        samples_rgb.append(x)
                        thermal_path = x.replace('fl_rgb', 'fl_ir_aligned')
                        samples_thermal.append(thermal_path)
                        rgb_first.append(True)
                    elif 'ir' in x:
                        samples_thermal.append(x)
                        rgb_path = x.replace('fl_ir_aligned', 'fl_rgb')
                        samples_rgb.append(rgb_path)
                        rgb_first.append(False)
        self.samples_rgb = samples_rgb
        self.samples_thermal = samples_thermal

        data_infos = []
        for i in range(len(self.samples_rgb)):
            info = {'img_prefix': self.data_prefix}
            info['rgb_info'] = {'filename': samples_rgb[i]}
            info['thermal_info'] = {'filename': samples_thermal[i]}
            info['modal'] = 'rgb' if rgb_first[i] else 'thermal'
            info['idx'] = int(i)
            data_infos.append(info)
        return data_infos
```
And I modified the __getitem__ function in my dataset file:
```
    def __getitem__(self, idx):
        rgb, thermal = self.data_source.get_img(idx)
        rgb = self.pipeline(rgb)
        thermal = self.pipeline(thermal)
        modal = self.data_source.get_modal(idx)
        if self.prefetch:
            rgb = torch.from_numpy(to_numpy(rgb))
            thermal = torch.from_numpy(to_numpy(thermal))
        img = torch.stack([rgb, thermal], dim=0)
        return dict(img=img, modal=modal, idx=idx)
```

**Comment by Dejavuvvw** [comment]
I found this is caused by the __getitem__ function. The value of the variable modal is obtained by the get_modal function of my data source. And the type of modal is str which can't be collated. The 'collate' operation is to compose a batch from the values of 'dict' and then return the tensor. The string-type variables cannot be composed into a tensor. So the error happened.
Solution: I have changed the type of modal to int.
