### ISSUE TITLE
when i train simmim,i got this error

### ISSUE THREAD

**Issue by wzr0108** [open-mmlab/mmselfsup#338]
```
Traceback (most recent call last):
  File "/disk/sdb/wzr/.conda/envs/wzr_env2/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/disk/sde/wzr/mms/mmselfsup/datasets/single_view.py", line 25, in __init__
    prefetch)
  File "/disk/sde/wzr/mms/mmselfsup/datasets/base.py", line 33, in __init__
    pipeline = [build_from_cfg(p, PIPELINES) for p in pipeline]
  File "/disk/sde/wzr/mms/mmselfsup/datasets/base.py", line 33, in <listcomp>
    pipeline = [build_from_cfg(p, PIPELINES) for p in pipeline]
  File "/disk/sdb/wzr/.conda/envs/wzr_env2/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'BlockwiseMaskGenerator is not in the pipeline registry'
```
I have already installed mmcv-full, mmcls and mmdet

The version are 
mmcls                   0.23.1
mmcv-full               1.5.0
mmdet                   2.23.0
mmselfsup               0.9.1

**Comment by fangyixiao18** [comment]
Sorry for the mistake. It is now called `SimMIMMaskGenerator`, please change the `type` here https://github.com/open-mmlab/mmselfsup/blob/master/configs/selfsup/_base_/datasets/imagenet_simmim.py#L23

**Comment by wzr0108** [comment]
> 

谢谢，现在可以跑了。
我还想请教一下，simmim中需要用到图片的类别标签吗

**Comment by fangyixiao18** [comment]
> > 
> 
> 谢谢，现在可以跑了。 我还想请教一下，simmim中需要用到图片的类别标签吗

不需要的
