### ISSUE TITLE
ModuleNotFoundError: No module named 'tools.benchmarks'

### ISSUE THREAD

**Issue by Yoooss** [open-mmlab/mmselfsup#343]
The command I use is "bash tools/benchmarks/mmdetection/mim_dist_train_c4.sh configs/benchmarks/mmdetection/voc0712/faster_rcnn_r50_c4_mstrain_2x_voc0712.py checkpoints/densecl_resnet50_8xb32-coslr-200e_in1k_20220225-8c7808fe.pth 1
".

And I got the error as below:

(mmselfsup) ls@ls:~/mmselfsup$ bash tools/benchmarks/mmdetection/mim_dist_train_c4.sh configs/benchmarks/mmdetection/voc0712/faster_rcnn_r50_c4_mstrain_2x_voc0712.py checkpoints/densecl_resnet50_8xb32-coslr-200e_in1k_20220225-8c7808fe.pth 1
+ CFG=configs/benchmarks/mmdetection/voc0712/faster_rcnn_r50_c4_mstrain_2x_voc0712.py
+ PRETRAIN=checkpoints/densecl_resnet50_8xb32-coslr-200e_in1k_20220225-8c7808fe.pth
+ GPUS=1
+ PY_ARGS=
++ echo configs/benchmarks/mmdetection/voc0712/faster_rcnn_r50_c4_mstrain_2x_voc0712
++ sed -e s/configs/work_dirs/g
++ echo checkpoints/densecl_resnet50_8xb32-coslr-200e_in1k_20220225-8c7808fe.pth
++ rev
++ cut -d/ -f 1
++ rev
+ WORK_DIR=work_dirs/benchmarks/mmdetection/voc0712/faster_rcnn_r50_c4_mstrain_2x_voc0712/densecl_resnet50_8xb32-coslr-200e_in1k_20220225-8c7808fe.pth
++ dirname tools/benchmarks/mmdetection/mim_dist_train_c4.sh
+ PYTHONPATH=tools/benchmarks/mmdetection/..:
+ mim train mmdet configs/benchmarks/mmdetection/voc0712/faster_rcnn_r50_c4_mstrain_2x_voc0712.py --launcher pytorch -G 1 --work-dir work_dirs/benchmarks/mmdetection/voc0712/faster_rcnn_r50_c4_mstrain_2x_voc0712/densecl_resnet50_8xb32-coslr-200e_in1k_20220225-8c7808fe.pth --cfg-options model.backbone.init_cfg.type=Pretrained model.backbone.init_cfg.checkpoint=checkpoints/densecl_resnet50_8xb32-coslr-200e_in1k_20220225-8c7808fe.pth model.roi_head.shared_head.init_cfg.type=Pretrained model.roi_head.shared_head.init_cfg.checkpoint=checkpoints/densecl_resnet50_8xb32-coslr-200e_in1k_20220225-8c7808fe.pth
Using port 29281 for synchronization. 
Training command is python -m torch.distributed.launch --nproc_per_node=1 --master_port=29281 /home/ls/anaconda3/envs/mmselfsup/lib/python3.7/site-packages/mmdet/.mim/tools/train.py configs/benchmarks/mmdetection/voc0712/faster_rcnn_r50_c4_mstrain_2x_voc0712.py --launcher pytorch --work-dir work_dirs/benchmarks/mmdetection/voc0712/faster_rcnn_r50_c4_mstrain_2x_voc0712/densecl_resnet50_8xb32-coslr-200e_in1k_20220225-8c7808fe.pth --cfg-options model.backbone.init_cfg.type=Pretrained model.backbone.init_cfg.checkpoint=checkpoints/densecl_resnet50_8xb32-coslr-200e_in1k_20220225-8c7808fe.pth model.roi_head.shared_head.init_cfg.type=Pretrained model.roi_head.shared_head.init_cfg.checkpoint=checkpoints/densecl_resnet50_8xb32-coslr-200e_in1k_20220225-8c7808fe.pth. 
Traceback (most recent call last):
  File "/home/ls/anaconda3/envs/mmselfsup/lib/python3.7/site-packages/mmcv/utils/misc.py", line 73, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/home/ls/anaconda3/envs/mmselfsup/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tools.benchmarks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ls/anaconda3/envs/mmselfsup/lib/python3.7/site-packages/mmdet/.mim/tools/train.py", line 220, in <module>
    main()
  File "/home/ls/anaconda3/envs/mmselfsup/lib/python3.7/site-packages/mmdet/.mim/tools/train.py", line 106, in main
    cfg = Config.fromfile(args.config)
  File "/home/ls/anaconda3/envs/mmselfsup/lib/python3.7/site-packages/mmcv/utils/config.py", line 337, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/home/ls/anaconda3/envs/mmselfsup/lib/python3.7/site-packages/mmcv/utils/misc.py", line 80, in import_modules_from_strings
    raise ImportError
ImportError
Killing subprocess 495
Traceback (most recent call last):
  File "/home/ls/anaconda3/envs/mmselfsup/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ls/anaconda3/envs/mmselfsup/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ls/anaconda3/envs/mmselfsup/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/ls/anaconda3/envs/mmselfsup/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/ls/anaconda3/envs/mmselfsup/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ls/anaconda3/envs/mmselfsup/bin/python', '-u', '/home/ls/anaconda3/envs/mmselfsup/lib/python3.7/site-packages/mmdet/.mim/tools/train.py', '--local_rank=0', 'configs/benchmarks/mmdetection/voc0712/faster_rcnn_r50_c4_mstrain_2x_voc0712.py', '--launcher', 'pytorch', '--work-dir', 'work_dirs/benchmarks/mmdetection/voc0712/faster_rcnn_r50_c4_mstrain_2x_voc0712/densecl_resnet50_8xb32-coslr-200e_in1k_20220225-8c7808fe.pth', '--cfg-options', 'model.backbone.init_cfg.type=Pretrained', 'model.backbone.init_cfg.checkpoint=checkpoints/densecl_resnet50_8xb32-coslr-200e_in1k_20220225-8c7808fe.pth', 'model.roi_head.shared_head.init_cfg.type=Pretrained', 'model.roi_head.shared_head.init_cfg.checkpoint=checkpoints/densecl_resnet50_8xb32-coslr-200e_in1k_20220225-8c7808fe.pth']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/ls/anaconda3/envs/mmselfsup/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/ls/anaconda3/envs/mmselfsup/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ls/anaconda3/envs/mmselfsup/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ls/anaconda3/envs/mmselfsup/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ls/anaconda3/envs/mmselfsup/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ls/anaconda3/envs/mmselfsup/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ls/anaconda3/envs/mmselfsup/lib/python3.7/site-packages/mim/commands/train.py", line 108, in cli
    other_args=other_args)
  File "/home/ls/anaconda3/envs/mmselfsup/lib/python3.7/site-packages/mim/commands/train.py", line 257, in train
    cmd, env=dict(os.environ, MASTER_PORT=str(port)))
  File "/home/ls/anaconda3/envs/mmselfsup/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '-m', 'torch.distributed.launch', '--nproc_per_node=1', '--master_port=29281', '/home/ls/anaconda3/envs/mmselfsup/lib/python3.7/site-packages/mmdet/.mim/tools/train.py', 'configs/benchmarks/mmdetection/voc0712/faster_rcnn_r50_c4_mstrain_2x_voc0712.py', '--launcher', 'pytorch', '--work-dir', 'work_dirs/benchmarks/mmdetection/voc0712/faster_rcnn_r50_c4_mstrain_2x_voc0712/densecl_resnet50_8xb32-coslr-200e_in1k_20220225-8c7808fe.pth', '--cfg-options', 'model.backbone.init_cfg.type=Pretrained', 'model.backbone.init_cfg.checkpoint=checkpoints/densecl_resnet50_8xb32-coslr-200e_in1k_20220225-8c7808fe.pth', 'model.roi_head.shared_head.init_cfg.type=Pretrained', 'model.roi_head.shared_head.init_cfg.checkpoint=checkpoints/densecl_resnet50_8xb32-coslr-200e_in1k_20220225-8c7808fe.pth']' returned non-zero exit status 1.

Thanks for your help.

**Comment by Yoooss** [comment]
I found the solution in the issue "https://github.com/open-mmlab/mmdetection/issues/7887" is uninstall the detectron2. And I run the command "pip uninstall detectron2" to remove the detectron2.
However, it still raised the same error as above.
May I ask how to fix it? Thanks for your help.

**Comment by fangyixiao18** [comment]
I checked the link of mmdet, do you have any other package which contains `tools`? we will update codes and try to avoid this error

**Comment by Yoooss** [comment]
I searched for the solution and uninstalled the detectron following one solution. However the error still raised and I still don't know how to solve it.
How could I check if I have other package which contains tools? 
May I get some help?Thanks for your help.

**Comment by Yoooss** [comment]
I checked my installed package again and found that it is "vissl" who caused this error because it contains tools.

**Comment by fangyixiao18** [comment]
> I checked my installed package again and found that it is "vissl" who caused this error because it contains tools.

Sorry for the inconvenience. We will update it in the future version to avoid this error.

**Comment by fangyixiao18** [comment]
Closing due to inactivity, please reopen if there are any further problems.
