### ISSUE TITLE
Error for deepcluster experiment

### ISSUE THREAD

**Issue by guochengqian** [open-mmlab/mmselfsup#41]
Hi OpenSelfSup team, 
Thank you for your amazing work. 
I wana report a bug I encountered in deepcluster exp here.

To repoduce:
`bash tools/dist_train.sh configs/selfsup/deepcluster/r50.py 4`

Meet error below:
```
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 2503/2503, 5.6 task/s, elapsed: 445s, ETA:     0s^[[B^[[B^[[B^[
PCA from dim 2048 to dim 256
Traceback (most recent call last):
  File "tools/train.py", line 145, in <module>
    main()
  File "tools/train.py", line 141, in main
    meta=meta)
  File "/home/qiang/codefiles/ssl/adv_ssl/openselfsup/apis/train.py", line 95, in train_model
    model, dataset, cfg, logger=logger, timestamp=timestamp, meta=meta)
  File "/home/qiang/codefiles/ssl/adv_ssl/openselfsup/apis/train.py", line 219, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/qiang/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 103, in run
    self.call_hook('before_run')
  File "/home/qiang/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 282, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/qiang/codefiles/ssl/adv_ssl/openselfsup/hooks/deepcluster_hook.py", line 43, in before_run
    self.deepcluster(runner)
  File "/home/qiang/codefiles/ssl/adv_ssl/openselfsup/hooks/deepcluster_hook.py", line 61, in deepcluster
    clustering_algo.cluster(features, verbose=True)
  File "/home/qiang/codefiles/ssl/adv_ssl/openselfsup/third_party/clustering.py", line 134, in cluster
    I, loss = run_kmeans(xb, self.k, verbose)
  File "/home/qiang/codefiles/ssl/adv_ssl/openselfsup/third_party/clustering.py", line 100, in run_kmeans
    losses = faiss.vector_to_array(clus.obj)
  File "/home/qiang/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/faiss/swigfaiss_avx2.py", line 1450, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Clustering, name)
  File "/home/qiang/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/faiss/swigfaiss_avx2.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'Clustering' object has no attribute 'obj'
Traceback (most recent call last):
  File "/home/qiang/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/qiang/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/qiang/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/qiang/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
```

My environment:
```
conda create -n open-mmlab python=3.7 -y  

conda activate open-mmlab  

conda install pytorch=1.6 torchvision cudatoolkit=10.1 faiss-gpu -c pytorch  

pip install -v -e .  # or "python setup.py develop"
```
 

Any suggestions on how to fix this? Is it a bug or I made some mistakes? 

Thank you!

With best regards, 
Guocheng

**Comment by guochengqian** [comment]
Fixed! 
The issue is from the version incompatibility of faiss-gpu. 

https://github.com/facebookresearch/faiss/issues/1179

**Comment by XiaohangZhan** [comment]
Glad to hear that.
