### ISSUE TITLE
How can I use multiple datasets during training?

### ISSUE THREAD

**Issue by foolhard** [open-mmlab/mmselfsup#489]
Hello, 

I have two datasets with the same classes. I would like to train a model by moco-v2 by using these two datasets together. 
I am trying to put path of both datasets in the config file like this (reference format from mmdet). 

`self.annfile = ['data/labels/dataset1_train.txt', 'data/labels/dataset2_train.txt']`

But I found the error below. I can do multiple datasets training in mmdet in this way, but failed in mmselfsup. I don't want to combine two dataset into one folder.

Could you help how to train multiple datasets in mmselfsup? 

Error message:

```
Traceback (most recent call last):
  File "/dfs/data/miniconda/envs/mmcls/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/dfs/data/open_mmlab/mmselfsup/mmselfsup/datasets/data_sources/base.py", line 47, in __init__
    self.data_infos = self.load_annotations()
  File "/dfs/data/open_mmlab/mmselfsup/mmselfsup/datasets/data_sources/imagenet.py", line 102, in load_annotations
    raise TypeError('ann_file must be a str or None')
TypeError: ann_file must be a str or None
```

**Comment by fangyixiao18** [comment]
Hi, you can use `ConcatDataset`, we have implemented [here](https://github.com/open-mmlab/mmselfsup/blob/master/mmselfsup/datasets/dataset_wrappers.py#L8), and the build_function is defined [here](https://github.com/open-mmlab/mmselfsup/blob/master/mmselfsup/datasets/builder.py#L35). 

You can try in config
```python
data = dict(
    samples_per_gpu=32,
    workers_per_gpu=4,
    train=[dict(type=dataset_type, ...), dict(type=dataset_type, ...)])

```

**Comment by foolhard** [comment]
Hello @fangyixiao18, 

I try `ConcatDataset` but found another error as below:
```
Traceback (most recent call last):
  File "tools/train.py", line 203, in <module>
    main()
  File "tools/train.py", line 185, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/dfs/data/open_mmlab/mmselfsup/mmselfsup/datasets/builder.py", line 38, in build_dataset
    dataset = ConcatDataset([build_dataset(c, default_args) for c in cfg])
  File "/dfs/data/open_mmlab/mmselfsup/mmselfsup/datasets/dataset_wrappers.py", line 20, in __init__
    self.CLASSES = datasets[0].CLASSES
AttributeError: 'MultiViewDataset' object has no attribute 'CLASSES'
```

Below is my data config file. 

```# dataset summary
data_source = 'ImageNet'
dataset_type = 'MultiViewDataset'
data = dict(
    samples_per_gpu=32,  # total 32*8=256
    workers_per_gpu=4,
    drop_last=True,
    train=[
        dict(
            type=dataset_type,
            data_source=dict(
                type=data_source,
                data_prefix='dataset1/train',
                ann_file='dataset1/train.txt',
            ),
            num_views=[2],
            pipelines=[train_pipeline],
            prefetch=prefetch,
        ),
         dict(
            type=dataset_type,
            data_source=dict(
                type=data_source,
                data_prefix='dataset2/val',
                ann_file='dataset2/val.txt',
            ),
            num_views=[2],
            pipelines=[train_pipeline],
            prefetch=prefetch,
        ),
    ]
)
```

I add `self.CLASSES = self.data_source.CLASSES`  into the **__init__()** of **MultiViewDataset**, and it works. 

Do you have any better solution?

**Comment by foolhard** [comment]
My final solution: 
Add self.CLASSES = self.data_source.CLASSES into the init() of MultiViewDataset, and it works.

Thanks a lot.
