### ISSUE TITLE
[Bug] TypeError: tuple indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by austinmw** [open-mmlab/mmselfsup#614]
### Branch

1.x branch (1.x version, such as `v1.0.0rc2`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmselfsup/issues) and [Discussions](https://github.com/open-mmlab/mmselfsup/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmselfsup.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmselfsup).

### Environment

```
sys.platform: linux
Python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) [GCC 10.3.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3: Tesla V100-SXM2-16GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.3, V11.3.109
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.12.1+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.1+cu113
OpenCV: 4.6.0
MMEngine: 0.3.2
MMCV: 2.0.0rc3
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.3
MMSelfSup: 1.0.0rc3+
```

### Describe the bug

When attempting to run `visualize_tsne.py` on a MAE checkpoint, I get a `TypeError` in `models/utils/data_preprocessor.py`.

### Reproduces the problem - code sample

command below

### Reproduces the problem - command or script

```bash
python /opt/mmselfsup/tools/analysis_tools/visualize_tsne.py /opt/ml/model/config.py --checkpoint /opt/ml/model/model.pth --work-dir /opt/ml/model/output --dataset-config /opt/ml/model/tsne_imagenet.py --max-num-class 20 --seed 0 --n-components 2 --perplexity 30.0 --early-exaggeration 12.0 --learning-rate 200.0 --n-iter 1000 --init random
```

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "/opt/mmselfsup/tools/analysis_tools/visualize_tsne.py", line 276, in <module>
    main()
  File "/opt/mmselfsup/tools/analysis_tools/visualize_tsne.py", line 227, in main
    features = extractor(model)
  File "/opt/mmselfsup/mmselfsup/models/utils/extractor.py", line 114, in __call__
    feats = nondist_forward_collect(func, self.data_loader,
  File "/opt/mmselfsup/mmselfsup/utils/collect.py", line 32, in nondist_forward_collect
    result = func(data)  # output: feat_dict
  File "/opt/mmselfsup/mmselfsup/models/utils/extractor.py", line 103, in func
    return self._forward_func(model, packed_data)
  File "/opt/mmselfsup/mmselfsup/models/utils/extractor.py", line 76, in _forward_func
    batch_inputs, batch_data_samples = model.data_preprocessor(packed_data)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/mmselfsup/mmselfsup/models/utils/data_preprocessor.py", line 44, in forward
    batch_inputs = [
  File "/opt/mmselfsup/mmselfsup/models/utils/data_preprocessor.py", line 45, in <listcomp>
    _input[:, [2, 1, 0], ...] for _input in batch_inputs
TypeError: tuple indices must be integers or slices, not tuple
```

**Comment by YuanLiuuuuuu** [comment]
Just now, I create a [PR](https://github.com/open-mmlab/mmselfsup/pull/616) to fix this bug. Please refer to it.

**Comment by YuanLiuuuuuu** [comment]
But currently we do not support T-SNE on MAE. This new feature will be coming soon, please stay tuned~

**Comment by austinmw** [comment]
Thanks!

**Comment by fangyixiao18** [comment]
Hello, we have fixed this bug, feel free to create new issues if you have any other questions~
