### ISSUE TITLE
The data format of  `PackSelfSupInputs` is conflict to the `ImgDataPreprocessor`[Bug] 

### ISSUE THREAD

**Issue by minipuding** [open-mmlab/mmselfsup#719]
### Branch

1.x branch (1.x version, such as `v1.0.0rc2`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmselfsup/issues) and [Discussions](https://github.com/open-mmlab/mmselfsup/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmselfsup.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmselfsup).

### Environment

sys.platform: linux
Python: 3.9.16 (main, Mar  8 2023, 14:00:05) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA A100-SXM4-80GB
CUDA_HOME: None
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
PyTorch: 1.12.1+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.1+cu113
OpenCV: 4.7.0
MMEngine: 0.6.0
MMCV: 2.0.0rc4
MMCV Compiler: n/a
MMCV CUDA Compiler: n/a
MMSelfSup: 1.0.0rc6+1534290

### Describe the bug

When I run movov2, there is an assertion error, the traceback are as follows:
```
AssertionError: If the mean has 3 values, the input tensor should in shape of (3, H, W), but got the tensor with shape t
orch.Size([3, 3, 224, 224])
Traceback (most recent call last):
  File "/nvme/xusijie/pjlab/projects/DD4PT/codes/tools/train.py", line 124, in <module>
    main()
  File "/nvme/xusijie/pjlab/projects/DD4PT/codes/tools/train.py", line 120, in main
    runner.train()
  File "/nvme/xusijie/pjlab/mmlab/mmengine/mmengine/runner/runner.py", line 1701, in train
    model = self.train_loop.run()  # type: ignore
  File "/nvme/xusijie/pjlab/mmlab/mmengine/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/nvme/xusijie/pjlab/mmlab/mmengine/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/nvme/xusijie/pjlab/mmlab/mmengine/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "/nvme/xusijie/pjlab/mmlab/mmengine/mmengine/model/wrappers/distributed.py", line 120, in train_step
    data = self.module.data_preprocessor(data, training=True)
  File "/nvme/xusijie/miniconda3/envs/sxu/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_i
mpl
    return forward_call(*input, **kwargs)
  File "/nvme/xusijie/pjlab/mmlab/mmengine/mmengine/model/base_model/data_preprocessor.py", line 252, in forward
    assert _batch_input.dim(
AssertionError: If the mean has 3 values, the input tensor should in shape of (3, H, W), but got the tensor with shape t
orch.Size([3, 3, 224, 224])
```
The key problem is that the format of `_batch_inputs` (generated by `PackSelfSupInputs` class) is a list and the element of this list is two 4-dim tensor like [32, 3, 244, 244]. So the data-flow enter the `if is_seq_of ...` rather than `elif isinstance(_batch_inputs, torch.Tensor)...` :
```python
class ImgDataPreprocessor(BaseDataPreprocessor):
    def forward:
        data = self.cast_data(data)  # type: ignore
        _batch_inputs = data['inputs']
        # Process data with `pseudo_collate`.
        if is_seq_of(_batch_inputs, torch.Tensor):
            batch_inputs = []
            for _batch_input in _batch_inputs:
                # channel transform
                if self._channel_conversion:
                    _batch_input = _batch_input[[2, 1, 0], ...]
                # Convert to float after channel conversion to ensure
                # efficiency
                _batch_input = _batch_input.float()
                # Normalization.
                if self._enable_normalize:
                    if self.mean.shape[0] == 3:
                        assert _batch_input.dim(
                        ) == 3 and _batch_input.shape[0] == 3, (
                            'If the mean has 3 values, the input tensor '
                            'should in shape of (3, H, W), but got the tensor '
                            f'with shape {_batch_input.shape}')
                    _batch_input = (_batch_input - self.mean) / self.std
                batch_inputs.append(_batch_input)
            # Pad and stack Tensor.
            batch_inputs = stack_batch(batch_inputs, self.pad_size_divisor,
                                       self.pad_value)
        # Process data with `default_collate`.
        elif isinstance(_batch_inputs, torch.Tensor):
            assert _batch_inputs.dim() == 4, (
                'The input of `ImgDataPreprocessor` should be a NCHW tensor '
                'or a list of tensor, but got a tensor with shape: '
                f'{_batch_inputs.shape}')
            if self._channel_conversion:
                _batch_inputs = _batch_inputs[:, [2, 1, 0], ...]
            # Convert to float after channel conversion to ensure
            # efficiency
            _batch_inputs = _batch_inputs.float()
            if self._enable_normalize:
                _batch_inputs = (_batch_inputs - self.mean) / self.std
            h, w = _batch_inputs.shape[2:]
            target_h = math.ceil(
                h / self.pad_size_divisor) * self.pad_size_divisor
            target_w = math.ceil(
                w / self.pad_size_divisor) * self.pad_size_divisor
            pad_h = target_h - h
            pad_w = target_w - w
            batch_inputs = F.pad(_batch_inputs, (0, pad_w, 0, pad_h),
                                 'constant', self.pad_value)
        else:
            raise TypeError('Output of `cast_data` should be a dict of '
                            'list/tuple with inputs and data_samples, '
                            f'but got {type(data)}： {data}')
        data['inputs'] = batch_inputs
        data.setdefault('data_samples', None)
        return data
```

**Comment by fangyixiao18** [comment]
It is because that when running mocov2, we need 2 views of images, which are formated in a list. so we use SelfSupDataPreprocessor instead of ImgDataPreprocessor

**Comment by minipuding** [comment]
> It is because that when running mocov2, we need 2 views of images, which are formated in a list. so we use SelfSupDataPreprocessor instead of ImgDataPreprocessor

But in the config file of `mocov2_resnet50_8xb32-coslr-200e_in1k.py` and the config it inherits, there is no `SelfSupDataPreprocessor ` type.
```python
# model settings
model = dict(
    type='MoCo',
    queue_len=65536,
    feat_dim=128,
    momentum=0.999,
    data_preprocessor=dict(
        mean=(123.675, 116.28, 103.53),
        std=(58.395, 57.12, 57.375),
        bgr_to_rgb=True),
    backbone=dict(
        type='ResNet',
        depth=50,
        in_channels=3,
        out_indices=[4],  # 0: conv-1, x: stage-x
        norm_cfg=dict(type='BN')),
    neck=dict(
        type='MoCoV2Neck',
        in_channels=2048,
        hid_channels=2048,
        out_channels=128,
        with_avg_pool=True),
    head=dict(
        type='ContrastiveHead',
        loss=dict(type='mmcls.CrossEntropyLoss'),
        temperature=0.2))

```

**Comment by fangyixiao18** [comment]
> > It is because that when running mocov2, we need 2 views of images, which are formated in a list. so we use SelfSupDataPreprocessor instead of ImgDataPreprocessor
> 
> But in the config file of `mocov2_resnet50_8xb32-coslr-200e_in1k.py` and the config it inherits, there is no `SelfSupDataPreprocessor ` type.
> 
> ```python
> # model settings
> model = dict(
>     type='MoCo',
>     queue_len=65536,
>     feat_dim=128,
>     momentum=0.999,
>     data_preprocessor=dict(
>         mean=(123.675, 116.28, 103.53),
>         std=(58.395, 57.12, 57.375),
>         bgr_to_rgb=True),
>     backbone=dict(
>         type='ResNet',
>         depth=50,
>         in_channels=3,
>         out_indices=[4],  # 0: conv-1, x: stage-x
>         norm_cfg=dict(type='BN')),
>     neck=dict(
>         type='MoCoV2Neck',
>         in_channels=2048,
>         hid_channels=2048,
>         out_channels=128,
>         with_avg_pool=True),
>     head=dict(
>         type='ContrastiveHead',
>         loss=dict(type='mmcls.CrossEntropyLoss'),
>         temperature=0.2))
> ```

we set the default in [code](https://github.com/open-mmlab/mmselfsup/blob/1.x/mmselfsup/models/algorithms/base.py#L55)
