### ISSUE TITLE
AssertionError: MMCV==2.0.0rc3 is used but incompatible.

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmselfsup#781]
**Checklist**

1. I have searched related issues but cannot get the expected help. yes
2. I have read the FAQ documentation but cannot get the expected help. yes

I am running this function:
python tools/analysis_tools/count_parameters.py configs/selfsup/simclr/simclr_resnet50_8xb32-coslr-200e_ACID.py

unfortunately, I am stuck in an error of the version of mmcv as bellow : 

Traceback (most recent call last):
  File "tools/analysis_tools/count_parameters.py", line 6, in <module>
    from mmselfsup.models import build_algorithm
  File "/home/shubbak/mmselfsup/mmselfsup/__init__.py", line 29, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==2.0.0rc3 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.

i think i am using old  version but not sure , so how to solve this error ?

**Comment by alaa-shubbak** [comment]
can you please help, until now I don't know how I can find those parameters. 
as I told you before my model was designed in the old version of myselfsup

**Comment by alaa-shubbak** [comment]
i am also trying your code in colab system , and all the time get this error 

`AssertionError: MMCV==2.2.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.`

even when try to install mmcv==2.0.0rc4 , mmcv==2.0.0rc5, mmcv==2.0.0rc6 all give error . it seems that there is a bug in your system , right?

**Comment by ayushnangia** [comment]
AssertionError: MMCV==2.1.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.

this even after using dockerfile
